name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python -m unittest tests/test_movie_search.py -v
    
    - name: Test basic functionality
      run: |
        python -c "
        from movie_search import search_movies
        results = search_movies('spy thriller', top_n=3)
        assert len(results) == 3
        assert 'similarity_score' in results.columns
        print('Basic functionality test passed!')
        "